import type { NoteItem } from "./types";

export const NOTE_COURSES = ["Matemática", "Estadística", "Física", "Programación", "Comunicación", "Historia", "Inglés", "Educación", "Otros"];

export const noteSeed: NoteItem[] = [
  { id: "n1", title: "Resumen de Distribuciones de Probabilidad", description: "Incluye distribución binomial, Poisson y normal con ejemplos aplicados.", course: "Estadística", materialType: "Resumen", authorName: "María Fernández", createdAt: "2026-05-08T12:10:00Z", status: "verificado", tags: ["probabilidad", "parcial"], file: { id: "f1", name: "distribuciones.pdf", size: 2300000, type: "application/pdf", fileType: "pdf", pages: 24 }, rating: { average: 5, count: 91 }, stats: { downloads: 340, saves: 122, comments: 21, views: 960 }, viewerState: { saved: false } },
  { id: "n2", title: "Guía de Límites y Continuidad", description: "Teoría + ejercicios frecuentes para primer parcial de Cálculo I.", course: "Matemática", materialType: "Guías", authorName: "Diego Morales", createdAt: "2026-05-09T09:00:00Z", status: "para_parcial", tags: ["cálculo", "límites"], file: { id: "f2", name: "limites-continuidad.pdf", size: 3200000, type: "application/pdf", fileType: "pdf", pages: 31 }, rating: { average: 4.8, count: 63 }, stats: { downloads: 280, saves: 95, comments: 15, views: 810 }, viewerState: { saved: false } },
  { id: "n3", title: "Ejercicios resueltos de Python", description: "Condicionales, bucles y funciones con soluciones explicadas paso a paso.", course: "Programación", materialType: "Ejercicios", authorName: "Andrés López", createdAt: "2026-05-07T16:30:00Z", status: "popular", tags: ["python", "práctica"], file: { id: "f3", name: "python-ejercicios.docx", size: 1800000, type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", fileType: "word", exercises: 52 }, rating: { average: 4.7, count: 74 }, stats: { downloads: 510, saves: 201, comments: 33, views: 1404 }, viewerState: { saved: true, isMine: true } },
  { id: "n4", title: "Fórmulas esenciales de Física I", description: "Resumen visual de cinemática, dinámica y trabajo con unidades.", course: "Física", materialType: "Fórmulas", authorName: "Sofía Díaz", createdAt: "2026-05-10T04:20:00Z", status: "verificado", tags: ["física", "fórmulas"], file: { id: "f4", name: "formulas-fisica.pdf", size: 2600000, type: "application/pdf", fileType: "pdf", pages: 14 }, rating: { average: 4.9, count: 56 }, stats: { downloads: 300, saves: 110, comments: 12, views: 760 }, viewerState: { saved: false } },
  { id: "n5", title: "Presentación: La independencia del Perú", description: "Diapositivas listas para exposición grupal con línea de tiempo.", course: "Historia", materialType: "PPT", authorName: "Mateo Vargas", createdAt: "2026-05-06T09:05:00Z", status: "para_parcial", tags: ["historia", "ppt"], file: { id: "f5", name: "independencia.pptx", size: 5100000, type: "application/vnd.openxmlformats-officedocument.presentationml.presentation", fileType: "ppt", slides: 18 }, rating: { average: 4.3, count: 32 }, stats: { downloads: 120, saves: 44, comments: 6, views: 333 }, viewerState: { saved: false } },
  { id: "n6", title: "Mapa conceptual de comprensión lectora", description: "Mapa en formato imagen para repasar ideas clave de lectura crítica.", course: "Comunicación", materialType: "Imagen", authorName: "Camila Ruiz", createdAt: "2026-05-10T08:00:00Z", status: "nuevo", tags: ["lectura", "mapa"], file: { id: "f6", name: "mapa-comprension.png", size: 800000, type: "image/png", fileType: "image" }, rating: { average: 4.6, count: 18 }, stats: { downloads: 67, saves: 30, comments: 3, views: 220 }, viewerState: { saved: false } },
  { id: "n7", title: "Separata de Estadística Inferencial", description: "Teoría y ejemplos de pruebas de hipótesis para práctica calificada.", course: "Estadística", materialType: "Separatas", authorName: "María Fernández", createdAt: "2026-05-09T19:10:00Z", status: "actualizado", tags: ["inferencial", "separata"], file: { id: "f7", name: "separata-inferencial.pdf", size: 4100000, type: "application/pdf", fileType: "pdf", pages: 42 }, rating: { average: 4.7, count: 45 }, stats: { downloads: 230, saves: 88, comments: 9, views: 620 }, viewerState: { saved: false } },
  { id: "n8", title: "Pack de ejercicios de Cálculo I", description: "Banco de problemas con respuestas para repaso final.", course: "Matemática", materialType: "Ejercicios", authorName: "Diego Morales", createdAt: "2026-05-07T12:40:00Z", status: "popular", tags: ["cálculo", "repaso"], file: { id: "f8", name: "calculo-pack.zip", size: 14200000, type: "application/zip", fileType: "zip", exercises: 80 }, rating: { average: 4.9, count: 74 }, stats: { downloads: 540, saves: 210, comments: 35, views: 1504 }, viewerState: { saved: true, isMine: true } },
];
