"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import { UniversityCalendarPreview } from "@/components/university/UniversityCalendarPreview";
import { UniversityFilters } from "@/components/university/UniversityFilters";
import { UniversityHeader } from "@/components/university/UniversityHeader";
import { UniversityItemCard } from "@/components/university/UniversityItemCard";
import { UniversitySidebar } from "@/components/university/UniversitySidebar";
import { useUniversity } from "@/hooks/useUniversity";

export default function UniversidadPage() {
  const params = useSearchParams();
  const router = useRouter();
  const [showHelp, setShowHelp] = useState(false);
  const [showSuggest, setShowSuggest] = useState(false);
  const [helpFilter, setHelpFilter] = useState("Todos");
  const [helpQuery, setHelpQuery] = useState("");
  const { items, selectedFilter, setSelectedFilter, selectedDay, setSelectedDay, saveItem, shareItem, addToCalendar, downloadFile, toast, addSuggestion, saveDraft, showToast } = useUniversity(params.get("q") ?? "");

  const contacts = useMemo(() => [
    { name: "Secretaría Académica", area: "Secretaría", desc: "Consultas académicas y constancias", email: "secretaria@crunedu.local", schedule: "Lun-Vie 8:00 a. m. - 5:00 p. m.", location: "Pabellón A" },
    { name: "Tesorería", area: "Tesorería", desc: "Pagos y estados de cuenta", email: "tesoreria@crunedu.local", schedule: "Lun-Vie 9:00 a. m. - 4:30 p. m.", location: "Pabellón B" },
    { name: "Bienestar Universitario", area: "Bienestar", desc: "Becas y apoyo estudiantil", email: "bienestar@crunedu.local", schedule: "Lun-Vie 8:30 a. m. - 5:00 p. m.", location: "Edificio Bienestar" },
    { name: "Biblioteca", area: "Biblioteca", desc: "Préstamos y recursos", email: "biblioteca@crunedu.local", schedule: "Lun-Sáb 8:00 a. m. - 8:00 p. m.", location: "Biblioteca central" },
    { name: "Soporte técnico", area: "Soporte", desc: "Soporte de sistemas", email: "soporte@crunedu.local", schedule: "Lun-Vie 8:00 a. m. - 6:00 p. m.", location: "Centro TIC" },
    { name: "Mesa de partes", area: "Trámites", desc: "Recepción de documentos", email: "mesadepartes@crunedu.local", schedule: "Lun-Vie 8:00 a. m. - 4:00 p. m.", location: "Entrada principal" },
  ], []);
  const filteredContacts = contacts.filter((c) => (helpFilter === "Todos" || c.area === helpFilter) && `${c.name} ${c.desc}`.toLowerCase().includes(helpQuery.toLowerCase()));

  return <section className="space-y-5"><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-4"><div className="grid gap-4 lg:grid-cols-2"><UniversityHeader onSuggest={() => setShowSuggest(true)} onCalendar={() => router.push("/app/universidad/calendario")} onSaved={() => setSelectedFilter("Guardados")} /><UniversityCalendarPreview selectedDay={selectedDay ?? 14} onSelectDay={(day) => { setSelectedDay(day); showToast(`Filtrando por el ${day} de mayo.`); }} /></div><UniversityFilters selected={selectedFilter} onChange={setSelectedFilter} /><div className="space-y-3">{items.length ? items.map((item) => <UniversityItemCard key={item.id} item={item} onSave={() => saveItem(item.id)} onShare={() => void shareItem(item.id)} onCalendar={addToCalendar} onDownload={() => downloadFile(item)} />) : <div className="rounded-2xl border bg-white p-6 text-center"><p className="text-sm text-slate-600">No hay información disponible para este filtro.</p><button onClick={() => setShowSuggest(true)} className="mt-3 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Sugerir información</button></div>}</div></div><UniversitySidebar onHelp={() => setShowHelp(true)} onMostConsulted={(q) => router.push(`/app/universidad?q=${encodeURIComponent(q)}`)} onViewAllEvents={() => router.push("/app/universidad/calendario?tipo=evento")} /></div>
  {showHelp ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4"><div className="w-full max-w-3xl rounded-2xl bg-white p-5"><h2 className="text-xl font-bold">Ayuda y contacto</h2><p className="text-sm text-slate-600">Encuentra el contacto correcto según el área o trámite que necesitas.</p><input value={helpQuery} onChange={(e) => setHelpQuery(e.target.value)} placeholder="Buscar área o trámite" className="mt-3 w-full rounded-lg border px-3 py-2 text-sm" /><div className="mt-2 flex flex-wrap gap-2">{["Todos", "Secretaría", "Tesorería", "Bienestar", "Biblioteca", "Soporte", "Admisión", "Trámites"].map((f) => <button key={f} onClick={() => setHelpFilter(f)} className={`rounded-full border px-2 py-1 text-xs ${helpFilter === f ? "bg-indigo-600 text-white" : "bg-white"}`}>{f}</button>)}</div><div className="mt-3 max-h-80 space-y-2 overflow-y-auto">{filteredContacts.map((c) => <div key={c.name} className="rounded-xl border p-3 text-sm"><p className="font-semibold">{c.name}</p><p className="text-slate-600">{c.desc}</p><p>{c.email}</p><p className="text-xs text-slate-500">{c.schedule} · {c.location}</p><button onClick={() => { navigator.clipboard.writeText(c.email); showToast("Correo copiado."); }} className="mt-2 rounded border px-2 py-1 text-xs">Copiar correo</button></div>)}</div><button className="mt-3 rounded border px-3 py-2" onClick={() => setShowHelp(false)}>Cerrar</button></div></div> : null}
  {showSuggest ? <SuggestModal onClose={() => setShowSuggest(false)} onDraft={saveDraft} onSend={addSuggestion} /> : null}
  {toast ? <div className="fixed bottom-5 right-5 rounded bg-slate-900 px-3 py-2 text-sm text-white">{toast}</div> : null}</section>;
}

function SuggestModal({ onClose, onDraft, onSend }: { onClose: () => void; onDraft: (payload: unknown) => void; onSend: (payload: any) => void }) {
  const [form, setForm] = useState({ type: "tramite", title: "", description: "", area: "", date: "", location: "", externalUrl: "" });
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-5"><h2 className="text-xl font-bold">Sugerir información</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><select className="rounded border px-3 py-2" value={form.type} onChange={(e) => setForm((f) => ({ ...f, type: e.target.value }))}>{["tramite", "convocatoria", "evento", "servicio", "guia", "aviso", "otro"].map((t) => <option key={t} value={t}>{t[0].toUpperCase() + t.slice(1)}</option>)}</select><input className="rounded border px-3 py-2" placeholder="Área relacionada" value={form.area} onChange={(e) => setForm((f) => ({ ...f, area: e.target.value }))} /><input className="rounded border px-3 py-2 sm:col-span-2" placeholder="Título" value={form.title} onChange={(e) => setForm((f) => ({ ...f, title: e.target.value }))} /><textarea className="rounded border px-3 py-2 sm:col-span-2" placeholder="Descripción" value={form.description} onChange={(e) => setForm((f) => ({ ...f, description: e.target.value }))} /><input type="date" className="rounded border px-3 py-2" value={form.date} onChange={(e) => setForm((f) => ({ ...f, date: e.target.value }))} /><input className="rounded border px-3 py-2" placeholder="Ubicación" value={form.location} onChange={(e) => setForm((f) => ({ ...f, location: e.target.value }))} /><input className="rounded border px-3 py-2 sm:col-span-2" placeholder="Enlace opcional" value={form.externalUrl} onChange={(e) => setForm((f) => ({ ...f, externalUrl: e.target.value }))} /></div><div className="mt-4 flex justify-end gap-2"><button onClick={onClose} className="rounded border px-3 py-2">Cancelar</button><button onClick={() => onDraft(form)} className="rounded border px-3 py-2">Guardar borrador</button><button onClick={() => { onSend({ id: `s-${Date.now()}`, type: form.type === "otro" ? "aviso" : form.type, title: form.title, description: form.description, area: form.area || "Trámites", category: "Sugerencias", visibility: "sugerido", status: ["pendiente_revision"], startDate: form.date || undefined, location: form.location || undefined, externalUrl: form.externalUrl || undefined, tags: ["sugerencia"], stats: { views: 0, saves: 0, shares: 0 }, viewerState: { saved: false } }); onClose(); }} className="rounded bg-indigo-600 px-3 py-2 text-white">Enviar sugerencia</button></div></div></div>;
}
