import { useEffect, useMemo, useState } from "react";
import { QUESTION_COURSES } from "./question-data";
import type { QuestionFile, QuestionImage } from "./types";

const IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];
const FILE_TYPES = ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.ms-powerpoint", "application/vnd.openxmlformats-officedocument.presentationml.presentation", "application/zip"];

export function CreateQuestionModal({ open, initialTitle, onClose, onSubmit, onSaveDraft }: { open: boolean; initialTitle?: string; onClose: () => void; onSubmit: (v: { title: string; description: string; course: string; tags: string[]; images: QuestionImage[]; files: QuestionFile[] }) => void; onSaveDraft: (v: { title: string; description: string; course: string; tags: string[]; images: QuestionImage[]; files: QuestionFile[] }) => void }) {
  const [title, setTitle] = useState(initialTitle ?? ""); const [description, setDescription] = useState(""); const [course, setCourse] = useState(""); const [tags, setTags] = useState<string[]>([]); const [tag, setTag] = useState("");
  const [images, setImages] = useState<QuestionImage[]>([]); const [files, setFiles] = useState<QuestionFile[]>([]); const [error, setError] = useState<string | null>(null);

  useEffect(() => { if (!open) return; setError(null); }, [open]);
  useEffect(() => () => { images.forEach((image) => { if (image.url.startsWith("blob:")) URL.revokeObjectURL(image.url); }); }, [images]);
  const payload = useMemo(() => ({ title, description, course, tags, images, files }), [title, description, course, tags, images, files]);
  if (!open) return null;

  return <div className="fixed inset-0 z-50 bg-black/40 p-4"><div className="mx-auto max-w-2xl rounded-2xl bg-white p-4"><h3 className="text-xl font-bold">Hacer pregunta</h3><select className="mt-2 w-full rounded border p-2" value={course} onChange={(e)=>setCourse(e.target.value)}><option value="">Selecciona curso</option>{QUESTION_COURSES.map(c=><option key={c}>{c}</option>)}</select><input className="mt-2 w-full rounded border p-2" value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Ej: ¿Cómo resuelvo este límite cuando x tiende a 0?" /><textarea className="mt-2 w-full rounded border p-2" value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Explica qué necesitas resolver..." />
  <div className="mt-2 grid gap-2 md:grid-cols-2"><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(e)=>{const selected=Array.from(e.target.files??[]); if(selected.length+images.length>4){setError("Solo puedes agregar hasta 4 imágenes."); return;} for(const file of selected){ if(!IMAGE_TYPES.includes(file.type)){setError("Formato no permitido."); return;} if(file.size>5*1024*1024){setError("La imagen supera el tamaño máximo de 5 MB."); return;} } setError(null); setImages((prev)=>[...prev,...selected.map((f)=>({id:`img-${Date.now()}-${f.name}`,url:URL.createObjectURL(f),alt:f.name}))]); }} className="rounded border p-2 text-xs" />
  <input type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.zip" onChange={(e)=>{const file=e.target.files?.[0]; if(!file) return; if(files.length>=1){setError("Solo puedes adjuntar un archivo principal."); return;} if(!FILE_TYPES.includes(file.type)){setError("Formato no permitido."); return;} if(file.size>25*1024*1024){setError("El archivo supera el tamaño máximo de 25 MB."); return;} setError(null); setFiles([{id:`f-${Date.now()}`,name:file.name,size:file.size,type:file.type}]); }} className="rounded border p-2 text-xs" /></div>
  {images.length>0?<div className="mt-2 flex gap-2">{images.map((img)=><img key={img.id} src={img.url} alt={img.alt??"Adjunto"} className="h-14 w-14 rounded object-cover" loading="lazy" />)}</div>:null}
  {files[0]?<div className="mt-2 rounded border p-2 text-xs">{files[0].name} · {Math.round(files[0].size/1024)} KB <button className="ml-2 text-red-600" onClick={()=>setFiles([])}>Quitar</button></div>:null}
  <div className="mt-2 flex gap-2"><input value={tag} onChange={(e)=>setTag(e.target.value)} className="rounded border p-2" placeholder="etiqueta" /><button onClick={()=>{const t=tag.trim().toLowerCase(); if(t && !tags.includes(t) && tags.length<8) setTags([...tags,t]); setTag("");}} className="rounded border px-2">Agregar</button></div><div className="mt-1 flex gap-1">{tags.map(t=><span key={t} className="rounded bg-slate-100 px-2 py-1 text-xs">{t}</span>)}</div>{error?<p className="mt-2 text-sm text-red-600">{error}</p>:null}<div className="mt-4 flex justify-end gap-2"><button onClick={()=>onSaveDraft(payload)} className="rounded border px-3 py-2">Guardar borrador</button><button onClick={onClose} className="rounded border px-3 py-2">Cancelar</button><button onClick={()=>onSubmit(payload)} className="rounded bg-indigo-600 px-3 py-2 text-white">Publicar pregunta</button></div></div></div>;
}
