import { useState } from "react";
import { QUESTION_COURSES } from "./question-data";
import type { QuestionFile, QuestionImage } from "./types";

export function CreateQuestionModal({ open, initialTitle, onClose, onSubmit }: { open: boolean; initialTitle?: string; onClose: () => void; onSubmit: (v: { title: string; description: string; course: string; tags: string[]; images: QuestionImage[]; files: QuestionFile[] }) => void }) {
  const [title, setTitle] = useState(initialTitle ?? ""); const [description, setDescription] = useState(""); const [course, setCourse] = useState(""); const [tags, setTags] = useState<string[]>([]); const [tag, setTag] = useState("");
  if (!open) return null;
  return <div className="fixed inset-0 z-50 bg-black/40 p-4"><div className="mx-auto max-w-2xl rounded-2xl bg-white p-4"><h3 className="text-xl font-bold">Hacer pregunta</h3><select className="mt-2 w-full rounded border p-2" value={course} onChange={(e)=>setCourse(e.target.value)}><option value="">Selecciona curso</option>{QUESTION_COURSES.map(c=><option key={c}>{c}</option>)}</select><input className="mt-2 w-full rounded border p-2" value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Ej: ¿Cómo resuelvo este límite cuando x tiende a 0?" /><textarea className="mt-2 w-full rounded border p-2" value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Explica qué necesitas resolver..." /><div className="mt-2 flex gap-2"><input value={tag} onChange={(e)=>setTag(e.target.value)} className="rounded border p-2" placeholder="etiqueta" /><button onClick={()=>{const t=tag.trim().toLowerCase(); if(t && !tags.includes(t) && tags.length<8) setTags([...tags,t]); setTag("");}} className="rounded border px-2">Agregar</button></div><div className="mt-1 flex gap-1">{tags.map(t=><span key={t} className="rounded bg-slate-100 px-2 py-1 text-xs">{t}</span>)}</div><div className="mt-4 flex justify-end gap-2"><button onClick={onClose} className="rounded border px-3 py-2">Cancelar</button><button onClick={()=>onSubmit({ title, description, course, tags, images: [], files: [] })} className="rounded bg-indigo-600 px-3 py-2 text-white">Publicar pregunta</button></div></div></div>;
}
