import type { QuestionItem } from "./types";

const now = Date.now();
const ago = (h: number) => new Date(now - h * 3600000).toISOString();

export const QUESTION_COURSES = ["Matemática", "Estadística", "Física", "Programación", "Comunicación", "Historia", "Inglés", "Educación", "Otros"];

export const initialQuestions: QuestionItem[] = [
  { id: "q1", title: "¿Cómo resuelvo este límite cuando x tiende a 0?", description: "Intenté con factorización pero no logro simplificar.", course: "Matemática", authorName: "Lucía Ramos", createdAt: ago(3), status: "sin_responder", tags: ["límites", "cálculo"], images: [{ id: "i1", url: "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=300", alt: "Ejercicio" }], stats: { answers: 0, votes: 7, views: 54, saves: 3 }, viewerState: { voted: false, saved: false, isMine: true } },
  { id: "q2", title: "Ayuda con este ejercicio de distribución normal", description: "No entiendo cómo hallar z y la probabilidad acumulada.", course: "Estadística", authorName: "Diego Flores", createdAt: ago(8), status: "respondida", tags: ["normal", "probabilidad"], files: [{ id: "f1", name: "Ejercicio_Distribucion.pdf", size: 152000, type: "application/pdf" }], stats: { answers: 2, votes: 18, views: 140, saves: 12 }, viewerState: { voted: true, saved: true }, answersPreview: [{ id: "a1", authorName: "María Salas", content: "Primero estandariza usando z=(x-μ)/σ...", votes: 5, createdAt: ago(5) }] },
  { id: "q3", title: "¿Está bien mi algoritmo de ordenamiento en Python?", description: "Comparé bubble sort con insertion y no sé por qué tarda más.", course: "Programación", authorName: "Kevin Poma", createdAt: ago(15), status: "con_mejor_respuesta", tags: ["python", "algoritmos"], stats: { answers: 4, votes: 25, views: 220, saves: 15 }, viewerState: { voted: false, saved: false }, bestAnswer: { id: "a2", authorName: "Andrea Quispe", content: "Tu implementación repite ciclos innecesarios. Puedes cortar cuando no hay swaps.", votes: 16, createdAt: ago(10), isBest: true }, answersPreview: [{ id: "a3", authorName: "Andrea Quispe", content: "Tu implementación repite ciclos innecesarios...", votes: 16, createdAt: ago(10), isBest: true }] },
  { id: "q4", title: "¿Cómo identificar la idea principal de este texto?", description: "Me cuesta diferenciar tema e idea principal.", course: "Comunicación", authorName: "Rosa Vega", createdAt: ago(30), status: "resuelta", tags: ["comprensión", "lectura"], files: [{ id: "f2", name: "analisis_texto.docx", size: 88000, type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" }], stats: { answers: 3, votes: 12, views: 95, saves: 8 }, viewerState: { voted: false, saved: false }, bestAnswer: { id: "a4", authorName: "Miguel Torres", content: "Busca la oración que resume el propósito del párrafo y verifica si el resto la desarrolla.", votes: 9, createdAt: ago(24), isBest: true } },
  { id: "q5", title: "¿Alguien puede explicarme esta ley de Ohm?", description: "Es urgente para el laboratorio de mañana.", course: "Física", authorName: "Ana Huamán", createdAt: ago(1), status: "urgente", tags: ["electricidad", "ohm"], images: [{ id: "i2", url: "https://images.unsplash.com/photo-1581092921461-eab10380f1a8?w=300", alt: "Circuito" }], stats: { answers: 1, votes: 10, views: 60, saves: 6 }, viewerState: { voted: false, saved: false }, answersPreview: [{ id: "a5", authorName: "Jorge Ruiz", content: "La corriente es proporcional al voltaje e inversa a la resistencia (I=V/R).", votes: 4, createdAt: ago(0.5) }] },
];
