import type { UniversityCalendarEvent, UniversityItem } from "./types";

export const universityItemsFallback: UniversityItem[] = [
  { id: "u1", type: "tramite", title: "Matrícula extemporánea 2026-2", description: "Proceso habilitado para estudiantes con observaciones académicas.", area: "Secretaría Académica", category: "Matrícula", visibility: "oficial", status: ["urgente", "oficial", "proximo_cierre"], deadline: "2026-05-15", tags: ["matrícula", "académico"], stats: { views: 1420, saves: 230, shares: 42 }, viewerState: { saved: false } },
  { id: "u2", type: "convocatoria", title: "Bolsa de trabajo UNI: inscripción abierta", description: "Postula a vacantes de prácticas preprofesionales hasta fin de mes.", area: "Bolsa de trabajo", category: "Bolsa de trabajo", visibility: "publico", status: ["abierto", "nuevo"], deadline: "2026-05-31", tags: ["empleabilidad", "convocatoria"], stats: { views: 860, saves: 165, shares: 55 }, viewerState: { saved: false } },
  { id: "u3", type: "evento", title: "Cine universitario: función especial este viernes", description: "Proyección y conversatorio sobre cine peruano contemporáneo.", area: "Cultura", category: "Cultura", visibility: "publico", status: ["nuevo"], startDate: "2026-05-14", time: "19:00", location: "Aula Magna", tags: ["cine", "cultura"], stats: { views: 640, saves: 122, shares: 40 }, viewerState: { saved: false } },
  { id: "u4", type: "guia", title: "Cómo solicitar una constancia de estudios", description: "Guía paso a paso con requisitos y tiempos de respuesta.", area: "Secretaría Académica", category: "Trámites", visibility: "oficial", status: ["oficial", "actualizado"], tags: ["constancia", "trámite"], stats: { views: 2030, saves: 410, shares: 88 }, viewerState: { saved: true }, file: { id: "f1", name: "requisitos-constancia.pdf", type: "pdf", size: 324000 } },
  { id: "u5", type: "convocatoria", title: "Beca alimentaria 2026: postulación", description: "Convocatoria para estudiantes en situación de vulnerabilidad.", area: "Bienestar Universitario", category: "Becas", visibility: "oficial", status: ["abierto", "proximo_cierre"], deadline: "2026-05-18", tags: ["becas", "bienestar"], stats: { views: 1110, saves: 301, shares: 61 }, viewerState: { saved: false } },
  { id: "u6", type: "tramite", title: "Reserva de matrícula", description: "Activa tu reserva para no perder vacante del próximo ciclo.", area: "Secretaría Académica", category: "Matrícula", visibility: "publico", status: ["abierto"], deadline: "2026-05-31", tags: ["reserva", "matrícula"], stats: { views: 730, saves: 144, shares: 20 }, viewerState: { saved: false } },
  { id: "u7", type: "evento", title: "Taller de empleabilidad: CV y entrevista", description: "Sesión práctica para mejorar perfil profesional.", area: "Bolsa de trabajo", category: "Eventos", visibility: "publico", status: ["nuevo"], startDate: "2026-05-15", time: "16:00", location: "Aula 2", tags: ["taller", "empleabilidad"], stats: { views: 520, saves: 98, shares: 22 }, viewerState: { saved: false } },
  { id: "u8", type: "servicio", title: "Horario de atención de Tesorería", description: "Atención presencial de lunes a viernes para pagos y consultas.", area: "Tesorería", category: "Pagos", visibility: "oficial", status: ["oficial", "actualizado"], time: "Lun. a vie. 8:00 a. m. a 5:00 p. m.", location: "Oficina central", tags: ["pagos", "tesorería"], stats: { views: 980, saves: 220, shares: 27 }, viewerState: { saved: false } },
];

export const calendarEventsFallback: UniversityCalendarEvent[] = universityItemsFallback.flatMap((item) => {
  const date = item.startDate ?? item.deadline;
  if (!date) return [];
  return [{ id: `evt-${item.id}`, itemId: item.id, title: item.title, date, type: item.type, location: item.location, time: item.time }];
});
