import { Bookmark, CalendarPlus, Download, Megaphone, Share2 } from "lucide-react";
import Link from "next/link";
import type { UniversityItem } from "./types";

const icons = { tramite: "📝", convocatoria: "📣", evento: "🎉", servicio: "🧩", guia: "📘", aviso: "📌" };
const statusLabels: Record<string, string> = { urgente: "Urgente", oficial: "Oficial", nuevo: "Nuevo", abierto: "Abierto", actualizado: "Actualizado", proximo_cierre: "Próximo cierre" };

export function UniversityItemCard({ item, onSave, onShare, onCalendar, onDownload }: { item: UniversityItem; onSave: () => void; onShare: () => void; onCalendar: () => void; onDownload: () => void }) {
  const right = item.deadline ? `Cierra el ${item.deadline}` : item.startDate ? `${item.startDate}${item.time ? `, ${item.time}` : ""}` : "Actualizado hace 1 día";
  const primary = item.type === "tramite" ? "Ir al trámite" : item.type === "convocatoria" ? "Ver convocatoria" : item.type === "evento" ? "Ver evento" : item.type === "guia" ? "Ver guía" : item.type === "servicio" ? "Ver servicio" : "Ver información";
  return <article className="rounded-2xl border bg-white p-4 transition hover:shadow-sm"><div className="flex items-start gap-3"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-xl">{icons[item.type]}</div><div className="min-w-0 flex-1"><h3 className="truncate font-bold"><Link href={`/app/universidad/${item.id}`}>{item.title}</Link></h3><p className="line-clamp-2 text-sm text-slate-600">{item.description}</p><p className="mt-1 text-xs text-slate-500">{item.category} · {item.area} · {item.visibility}</p><div className="mt-2 flex flex-wrap gap-1">{item.status.map((s) => statusLabels[s] ? <span key={s} className="rounded-full bg-slate-100 px-2 py-0.5 text-[11px] text-slate-700">{statusLabels[s]}</span> : null)}</div></div><div className="w-44 shrink-0 text-right"><p className="text-xs font-semibold text-slate-700">{right}</p><Link href={`/app/universidad/${item.id}`} className="mt-2 inline-block rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-semibold text-white">{primary}</Link></div></div><div className="mt-3 flex flex-wrap gap-2 text-xs"><button onClick={onSave} className="rounded border px-2 py-1"><Bookmark className="mr-1 inline h-3.5 w-3.5" />{item.viewerState.saved ? "Guardado" : "Guardar"}</button><button onClick={onShare} className="rounded border px-2 py-1"><Share2 className="mr-1 inline h-3.5 w-3.5" />Compartir</button><button onClick={onCalendar} className="rounded border px-2 py-1"><CalendarPlus className="mr-1 inline h-3.5 w-3.5" />Agregar al calendario</button>{item.file ? <button onClick={onDownload} className="rounded border px-2 py-1"><Download className="mr-1 inline h-3.5 w-3.5" />Descargar requisitos</button> : null}</div></article>;
}
