import { ChevronLeft, ChevronRight } from "lucide-react";
import Link from "next/link";

const eventDots: Record<number, string[]> = { 14: ["evento"], 15: ["evento", "tramite"], 16: ["servicio"], 18: ["convocatoria"], 20: ["becas"], 22: ["cultura"] };
const colorByType: Record<string, string> = { tramite: "bg-violet-500", evento: "bg-orange-500", convocatoria: "bg-green-500", servicio: "bg-blue-500", becas: "bg-purple-300", cultura: "bg-pink-400" };

export function UniversityCalendarPreview({ selectedDay, onSelectDay }: { selectedDay: number; onSelectDay: (day: number) => void }) {
  return <div className="rounded-2xl border bg-white p-4"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><button className="rounded-lg border p-1.5 text-slate-600" aria-label="Mes anterior"><ChevronLeft className="h-4 w-4" /></button><h2 className="font-bold">Mayo 2026</h2><button className="rounded-lg border p-1.5 text-slate-600" aria-label="Mes siguiente"><ChevronRight className="h-4 w-4" /></button></div><Link className="text-sm font-medium text-indigo-600" href="/app/universidad/calendario">Ver calendario completo</Link></div><div className="grid grid-cols-7 gap-1 text-center text-xs">{Array.from({ length: 31 }).map((_, i) => { const day = i + 1; const dots = eventDots[day] ?? []; return <button key={day} onClick={() => onSelectDay(day)} className={`rounded-md border px-1 py-1.5 ${selectedDay === day ? "border-indigo-300 bg-indigo-50 text-indigo-700" : "border-slate-100 bg-slate-50"}`}><span>{day}</span><span className="mt-1 flex justify-center gap-0.5">{dots.slice(0, 3).map((d, idx) => <span key={`${d}-${idx}`} className={`h-1.5 w-1.5 rounded-full ${colorByType[d]}`} />)}</span></button>; })}</div><p className="mt-3 text-xs text-slate-500">Trámites · Eventos · Convocatorias · Servicios</p></div>;
}
