FROM node:20-alpine

WORKDIR /workspace

RUN apk add --no-cache openssl bash

COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
COPY apps/api/package*.json ./apps/api/
COPY packages/database/package*.json ./packages/database/
COPY packages/shared/package*.json ./packages/shared/
COPY packages/ui/package*.json ./packages/ui/

RUN npm install

COPY . .
