import Link from "next/link";
import { Boost, Clock3, MapPin, MessageCircle, Send, ShieldCheck, Sparkles, Bookmark } from "lucide-react";
import type { MomentItem } from "./types";

function formatRelative(createdAt: string) {
  const diffMs = Date.now() - new Date(createdAt).getTime();
  const diffMin = Math.max(1, Math.round(diffMs / 60000));
  if (diffMin < 60) return `Hace ${diffMin} min`;
  const hours = Math.round(diffMin / 60);
  return `Hace ${hours} h`;
}

export function MomentInfoPanel({ moment, onBoost, onPass, onComment, onSave, onShare }: { moment: MomentItem; onBoost: ()=>void; onPass: ()=>void; onComment: ()=>void; onSave: ()=>void; onShare: ()=>void }) {
  return <div className="space-y-5 rounded-3xl border border-slate-200 bg-white p-5 md:p-6"><h2 className="text-3xl font-black tracking-tight text-slate-900">{moment.title}</h2><p className="text-base leading-relaxed text-slate-600">{moment.description}</p><div className="space-y-2 border-y border-slate-100 py-3 text-sm text-slate-600"><p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-slate-400" />{moment.location}</p><p className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-slate-400" />Expira en 23 h</p><p className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-slate-400" />{formatRelative(moment.createdAt)}</p></div><div className="flex flex-wrap gap-2">{moment.tags.map((tag)=><span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-medium text-slate-700" key={tag}>#{tag}</span>)}</div><div className="grid grid-cols-3 divide-x divide-slate-100 rounded-2xl border border-slate-200 bg-slate-50 px-2 py-3 text-center text-sm"><p><span className="block text-lg font-bold text-slate-900">{moment.stats.boosts}</span>impulsos</p><p><span className="block text-lg font-bold text-slate-900">{moment.stats.confirmations}</span>confirmaciones</p><p><span className="block text-lg font-bold text-slate-900">{moment.stats.comments}</span>comentarios</p></div><div className="grid grid-cols-2 gap-3"><button onClick={onBoost} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-4 py-3.5 font-semibold text-white shadow-md transition hover:brightness-110"><Boost className="h-4 w-4" />Impulsar</button><button onClick={onPass} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-300 bg-white px-4 py-3.5 font-semibold text-slate-800 transition hover:bg-slate-50"><ShieldCheck className="h-4 w-4" />Pasar</button></div><div className="grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><button onClick={onComment} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 font-medium transition hover:bg-slate-50">Comentar</button><button onClick={onSave} className="inline-flex items-center justify-center gap-1 rounded-xl border border-slate-200 bg-white px-3 py-2.5 font-medium transition hover:bg-slate-50"><Bookmark className="h-4 w-4" />Guardar</button><button onClick={onShare} className="inline-flex items-center justify-center gap-1 rounded-xl border border-slate-200 bg-white px-3 py-2.5 font-medium transition hover:bg-slate-50"><Send className="h-4 w-4" />Compartir</button><Link href={`/app/momentos/${moment.id}`} className="inline-flex items-center justify-center gap-1 rounded-xl border border-slate-200 bg-white px-3 py-2.5 font-medium transition hover:bg-slate-50"><MessageCircle className="h-4 w-4" />Ver detalles</Link></div></div>;
}
