import type {
  Companion,
  Conversation,
  ConversationMaterial,
  ConversationParticipant,
  ConversationRecording,
  ConversarUser,
  DebateStance,
  SharedLink,
} from './types';

export const mockConversarUsers: ConversarUser[] = [
  {
    id: 'user-lucia',
    name: 'Lucía Ramos',
    university: 'La Cantuta',
    career: 'Educación Matemática',
    isVerified: true,
  },
  {
    id: 'user-diego',
    name: 'Diego Huamán',
    university: 'La Cantuta',
    career: 'Historia',
  },
  {
    id: 'user-camila',
    name: 'Camila Paredes',
    university: 'La Cantuta',
    career: 'Física',
    isPremium: true,
  },
  {
    id: 'user-adrian',
    name: 'Adrián Torres',
    university: 'La Cantuta',
    career: 'Idiomas - Inglés',
  },
  {
    id: 'user-valeria',
    name: 'Valeria Salazar',
    university: 'La Cantuta',
    career: 'Ingeniería de Sistemas',
    isVerified: true,
  },
  {
    id: 'user-jose',
    name: 'José Mendoza',
    university: 'La Cantuta',
    career: 'Filosofía',
  },
  {
    id: 'user-melissa',
    name: 'Melissa Ccahuana',
    university: 'La Cantuta',
    career: 'Psicología',
    isPremium: true,
  },
];

export const mockRecordings: ConversationRecording[] = [
  {
    id: 'rec-proposiciones-cero',
    status: 'available',
    durationLabel: '42 min',
    audioUrl: 'https://audio.crunedu.local/proposiciones-desde-cero.mp3',
    plays: 128,
    createdAt: '2026-05-10T20:00:00.000Z',
  },
  {
    id: 'rec-ia-tareas',
    status: 'available',
    durationLabel: '36 min',
    audioUrl: 'https://audio.crunedu.local/ia-en-tareas-universitarias.mp3',
    plays: 201,
    createdAt: '2026-05-11T19:30:00.000Z',
  },
  {
    id: 'rec-revolucion-francesa',
    status: 'processing',
    durationLabel: '28 min',
    plays: 0,
    createdAt: '2026-05-12T22:15:00.000Z',
  },
  {
    id: 'rec-tecnicas-estudio',
    status: 'available',
    durationLabel: '31 min',
    audioUrl: 'https://audio.crunedu.local/tecnicas-de-estudio.mp3',
    plays: 93,
    createdAt: '2026-05-09T18:20:00.000Z',
  },
];

export const mockParticipants: ConversationParticipant[] = [
  { id: 'part-1', user: mockConversarUsers[0], status: 'host', joinedAt: '2026-05-14T19:00:00.000Z', role: 'Host' },
  { id: 'part-2', user: mockConversarUsers[1], status: 'speaking', joinedAt: '2026-05-14T19:03:00.000Z' },
  { id: 'part-3', user: mockConversarUsers[2], status: 'listening', joinedAt: '2026-05-14T19:05:00.000Z' },
  { id: 'part-4', user: mockConversarUsers[3], status: 'handRaised', joinedAt: '2026-05-14T19:07:00.000Z' },
  { id: 'part-5', user: mockConversarUsers[4], status: 'listening', joinedAt: '2026-05-14T19:09:00.000Z' },
];

export const mockMaterials: ConversationMaterial[] = [
  {
    id: 'mat-logic-pdf',
    title: 'Guía de proposiciones lógicas',
    type: 'pdf',
    size: '1.4 MB',
    url: 'https://files.crunedu.local/guia-proposiciones.pdf',
    uploadedBy: mockConversarUsers[0],
    uploadedAt: '2026-05-14T18:55:00.000Z',
  },
  {
    id: 'mat-historia-link',
    title: 'Cronología resumida de la Revolución Francesa',
    type: 'link',
    url: 'https://es.wikipedia.org/wiki/Revoluci%C3%B3n_francesa',
    uploadedBy: mockConversarUsers[1],
    uploadedAt: '2026-05-14T17:20:00.000Z',
  },
];

export const mockSharedLinks: SharedLink[] = [
  {
    id: 'link-meet-logic',
    title: 'Enlace Meet de repaso',
    url: 'https://meet.google.com/logic-verdad',
    type: 'meet',
    domain: 'meet.google.com',
    sharedBy: mockConversarUsers[0],
    sharedAt: '2026-05-14T18:50:00.000Z',
  },
  {
    id: 'link-video-ia',
    title: 'Video: IA y aprendizaje activo',
    url: 'https://www.youtube.com/watch?v=ia-aprendizaje',
    type: 'video',
    domain: 'www.youtube.com',
    sharedBy: mockConversarUsers[4],
    sharedAt: '2026-05-14T19:10:00.000Z',
  },
];

export const mockDebateStances: DebateStance[] = [
  {
    id: 'stance-favor',
    title: 'A favor',
    description: 'La IA personaliza el aprendizaje y mejora la productividad.',
    color: '#16a34a',
    participants: 6,
    arguments: [
      {
        id: 'arg-1',
        stanceId: 'stance-favor',
        content: 'Ayuda a resumir textos complejos y optimiza el tiempo de estudio.',
        author: mockConversarUsers[4],
        createdAt: '2026-05-14T19:12:00.000Z',
      },
    ],
  },
  {
    id: 'stance-contra',
    title: 'En contra',
    description: 'Puede generar dependencia y reducir el pensamiento crítico.',
    color: '#dc2626',
    participants: 4,
    arguments: [
      {
        id: 'arg-2',
        stanceId: 'stance-contra',
        content: 'Muchos estudiantes copian respuestas sin entender realmente.',
        author: mockConversarUsers[5],
        createdAt: '2026-05-14T19:14:00.000Z',
      },
    ],
  },
  {
    id: 'stance-depende',
    title: 'Depende del uso',
    description: 'Su impacto depende de la guía docente y de la ética académica.',
    color: '#2563eb',
    participants: 5,
    arguments: [
      {
        id: 'arg-3',
        stanceId: 'stance-depende',
        content: 'Con reglas claras, la IA puede complementar y no reemplazar el aprendizaje.',
        author: mockConversarUsers[6],
        createdAt: '2026-05-14T19:16:00.000Z',
      },
    ],
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-study-logic',
    type: 'study',
    status: 'live',
    title: 'Proposiciones lógicas y tablas de verdad',
    description: 'Repaso guiado para cachimbos con ejercicios paso a paso.',
    category: 'Matemática',
    course: 'Lógica Matemática',
    createdBy: mockConversarUsers[0],
    createdAt: '2026-05-14T18:45:00.000Z',
    visibility: 'university',
    isRecording: true,
    recording: mockRecordings[0],
    participants: mockParticipants,
    talkingCount: 2,
    listeningCount: 5,
    tags: ['lógica', 'tablas de verdad', 'cachimbos'],
    materials: [mockMaterials[0]],
    sharedLinks: [mockSharedLinks[0]],
  },
  {
    id: 'conv-open-historia',
    type: 'open',
    status: 'live',
    title: 'Revolución Francesa: causas y consecuencias',
    description: 'Conversación abierta para ordenar ideas clave antes del parcial.',
    category: 'Historia',
    createdBy: mockConversarUsers[1],
    createdAt: '2026-05-14T17:15:00.000Z',
    visibility: 'public',
    isRecording: false,
    recording: null,
    participants: mockParticipants.slice(1, 4),
    talkingCount: 1,
    listeningCount: 3,
    tags: ['historia moderna', 'parcial'],
    materials: [mockMaterials[1]],
    sharedLinks: [],
  },
  {
    id: 'conv-question-tecnicas',
    type: 'question',
    status: 'waiting',
    title: '¿Qué técnicas de estudio realmente funcionan?',
    description: 'Quiero escuchar métodos que sí funcionen para cursos pesados.',
    category: 'Vida universitaria',
    createdBy: mockConversarUsers[6],
    createdAt: '2026-05-14T16:40:00.000Z',
    visibility: 'university',
    isRecording: false,
    recording: null,
    participants: [mockParticipants[2]],
    talkingCount: 0,
    listeningCount: 1,
    tags: ['hábitos', 'organización', 'exámenes'],
    materials: [],
    sharedLinks: [mockSharedLinks[1]],
  },
  {
    id: 'conv-debate-ia',
    type: 'debate',
    status: 'live',
    title: '¿La inteligencia artificial mejora o perjudica el aprendizaje universitario?',
    description: 'Debate formal con posturas definidas y turnos por ronda.',
    category: 'Tecnología / Educación',
    createdBy: mockConversarUsers[4],
    createdAt: '2026-05-14T19:00:00.000Z',
    visibility: 'public',
    isRecording: true,
    recording: mockRecordings[1],
    participants: mockParticipants,
    talkingCount: 3,
    listeningCount: 7,
    tags: ['ia', 'ética', 'aprendizaje'],
    materials: [],
    sharedLinks: [mockSharedLinks[1]],
    debateStances: mockDebateStances,
  },
  {
    id: 'conv-finished-proposiciones',
    type: 'question',
    status: 'finished',
    title: 'No entiendo proposiciones lógicas',
    description: 'Espacio que se cerró luego de resolver ejercicios base.',
    category: 'Matemática',
    createdBy: mockConversarUsers[2],
    createdAt: '2026-05-13T21:00:00.000Z',
    visibility: 'private',
    isRecording: false,
    recording: mockRecordings[0],
    participants: mockParticipants.slice(0, 3),
    talkingCount: 1,
    listeningCount: 2,
    tags: ['apoyo', 'lógica'],
    materials: [mockMaterials[0]],
    sharedLinks: [],
    sourceConversationId: 'conv-study-logic',
  },
];

export const mockCompanions: Companion[] = [
  {
    id: 'comp-mate',
    user: mockConversarUsers[0],
    topics: ['Matemática', 'Lógica', 'Álgebra'],
    availability: 'Hoy 7:00 pm - 10:00 pm',
    description: 'Te ayudo a resolver ejercicios desde lo más básico.',
    canVoice: true,
  },
  {
    id: 'comp-historia',
    user: mockConversarUsers[1],
    topics: ['Historia', 'Historia del Perú'],
    availability: 'Mañana 6:00 pm - 9:00 pm',
    description: 'Repasamos cronologías y mapas conceptuales para parciales.',
    canVoice: true,
  },
  {
    id: 'comp-fisica',
    user: mockConversarUsers[2],
    topics: ['Física', 'Mecánica'],
    availability: 'Hoy 8:00 pm - 11:00 pm',
    description: 'Acompañamiento para problemas y laboratorio.',
    canVoice: true,
  },
  {
    id: 'comp-ingles',
    user: mockConversarUsers[3],
    topics: ['Inglés', 'Speaking', 'Reading'],
    availability: 'Lunes a viernes 5:00 pm - 7:00 pm',
    description: 'Práctica guiada de conversación y comprensión de textos.',
    canVoice: true,
  },
  {
    id: 'comp-programacion',
    user: mockConversarUsers[4],
    topics: ['Programación', 'TypeScript', 'Algoritmos'],
    availability: 'Hoy 9:00 pm - 11:30 pm',
    description: 'Mentoría rápida para tareas y proyectos de código.',
    canVoice: true,
  },
  {
    id: 'comp-filosofia',
    user: mockConversarUsers[5],
    topics: ['Filosofía', 'Ética', 'Argumentación'],
    availability: 'Sábados 4:00 pm - 8:00 pm',
    description: 'Discusión de textos y preparación para exposiciones.',
    canVoice: false,
  },
];
